export const projects = [
  {
    title: "Waverly",
    role: "Project Manager · Web3 Hackathon",
    type: "electric",
    typeLabel: "LEADERSHIP",
    summary: "Leading a cross-functional team through a four-month build for the TEKNOFEST Turkey Web3 Hackathon, aligning frontend and smart-contract delivery.",
    metrics: [{ value: "4", label: "team members" }, { value: "4 mo", label: "delivery cycle" }],
    skills: ["Roadmapping", "Agile", "Web3", "Stakeholders"],
    challenge: "Turn an ambitious Web3 concept into a competition-ready product under a fixed hackathon timeline.",
    moves: ["Mapped scope & milestones", "Synced frontend and smart-contract work", "Tracked blockers through Agile rituals"],
    outcome: "A four-person team stayed aligned through an active four-month delivery cycle toward the final round.",
    link: "",
  },
  {
    title: "Starlight 2025",
    role: "Technical PM & Product Designer",
    type: "water",
    typeLabel: "DELIVERY",
    summary: "Directed the product lifecycle of a live event platform—from stakeholder requirements and user journeys to responsive CRUD delivery.",
    metrics: [{ value: "7", label: "people led" }, { value: "200+", label: "transactions" }],
    skills: ["Product Strategy", "UX", "Database", "Delivery"],
    challenge: "Ship a public ticketing platform that could support a live campus event and high-volume access.",
    moves: ["Translated stakeholder needs", "Designed journeys and data flows", "Coordinated seven contributors"],
    outcome: "The platform went live and supported more than 200 successful ticket transactions.",
    link: "https://starlightumn2025.com/",
  },
  {
    title: "My Lawson Revamp",
    role: "Quality Assurance Intern",
    type: "grass",
    typeLabel: "QUALITY",
    summary: "Owned staging validation, test planning, API and database checks, regression cycles, and build distribution across two major releases.",
    metrics: [{ value: "50–100", label: "test scenarios" }, { value: "50+", label: "bugs found" }],
    skills: ["Qase", "Jira", "Postman", "TestFlight"],
    challenge: "Protect release quality across mobile flows, APIs, databases, and a changing staging environment.",
    moves: ["Built structured test suites", "Validated APIs and data", "Managed regression and build distribution"],
    outcome: "Identified 50+ issues across two major releases while supporting staging readiness end to end.",
    link: "",
  },
  {
    title: "Virtual Try-On",
    role: "Product Designer",
    type: "psychic",
    typeLabel: "RESEARCH",
    summary: "Designed the complete fitting-room journey and high-fidelity interaction states, then tested the concept at a campus showcase.",
    metrics: [{ value: "35+", label: "participants" }, { value: "1", label: "validated flow" }],
    skills: ["Figma", "Prototyping", "Usability", "User Flow"],
    challenge: "Make a virtual fitting-room concept intuitive enough for first-time users at a live showcase.",
    moves: ["Mapped the full user journey", "Prototyped interaction states", "Observed real participant behavior"],
    outcome: "Feedback from 35+ participants validated the core flow and exposed practical usability improvements.",
    link: "https://tryon-nine.vercel.app/",
  },
  {
    title: "AntriDok",
    role: "Developer & Accessibility Designer",
    type: "fire",
    typeLabel: "ENGINEERING",
    summary: "Co-developed a native clinic queue application with accessibility-first navigation tailored to elderly patients.",
    metrics: [{ value: "3", label: "team members" }, { value: "1", label: "native app" }],
    skills: ["Kotlin", "Mobile", "Accessibility", "Teamwork"],
    challenge: "Simplify clinic queue monitoring for patients, including elderly users with accessibility needs.",
    moves: ["Co-developed the native app", "Prioritized readable navigation", "Designed around real queue tasks"],
    outcome: "Delivered a native Kotlin prototype with an accessibility-first patient experience.",
    link: "https://github.com/FarrelNayakaaa/AntriDokter",
  },
];

export const experience = [
  { role: "Project Manager", company: "Waverly Team · TEKNOFEST", period: "Apr 2026 — Present", description: "Leading product scope, milestones, and cross-functional alignment for a Web3 platform." },
  { role: "Quality Assurance Intern", company: "PT Global Loyalty Indonesia", period: "Jan 2026 — Present", description: "Driving test planning, staging readiness, backend validation, and regression delivery for My Lawson Revamp." },
  { role: "Technical Project Manager & Product Designer", company: "Starlight 2025", period: "Jan 2025 — Nov 2025", description: "Leading a seven-person team from requirements through deployment for a live ticketing platform." },
  { role: "Operating System Lab Assistant", company: "Multimedia Nusantara University", period: "Feb 2025 — Jul 2025", description: "Mentored 70+ students through systems fundamentals, debugging, and technical problem-solving." },
];

export const skillGroups = [
  { icon: "01", kicker: "CORE TYPE", title: "Project Leadership", skills: ["Technical PM", "Agile / Scrum", "Roadmapping", "Risk Management", "Stakeholder Alignment"] },
  { icon: "02", kicker: "SUPPORT TYPE", title: "Quality & Product", skills: ["Test Planning", "API Testing", "UX Research", "Figma", "Accessibility"] },
  { icon: "03", kicker: "TECH TYPE", title: "Engineering Fluency", skills: ["JavaScript", "React", "Kotlin", "Python", "PostgreSQL", "MongoDB"] },
];

export const socialLinks = [
  { name: "LinkedIn", url: "https://www.linkedin.com/in/muhammad-farrel-87a776278" },
  { name: "GitHub", url: "https://github.com/FarrelNayakaaa" },
  { name: "Instagram", url: "https://www.instagram.com/farrelnayakaa/" },
];
